---
db_user: root
db_password: password
db_url: localhost
db_name: test01
db_table_name: ZIP_POP
user_agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-us) AppleWebKit/533.17.8
  (KHTML, like Gecko) Version/5.0.1 Safari/533.17.8 );
