---
db_user: root
db_password: password
db_url: localhost
db_name: stock4_development
db_table_name_stock_symbols: stock_symbols
db_table_name_stock_quotes: stock_quotes
user_agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4; en-us) AppleWebKit/533.17.8
  (KHTML, like Gecko) Version/5.0.1 Safari/533.17.8 );
